<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Communication.API\Communication.API.csproj" />
    <ProjectReference Include="..\..\Exceptions.Handling\Exceptions.Handling.csproj" />
    <ProjectReference Include="..\Events.Application\Events.Application.csproj" />
    <ProjectReference Include="..\Events.Domain\Events.Domain.csproj" />
  </ItemGroup>

</Project>
