services:
  account.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:5001"
    networks:
      - my-network 

  bookings.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5002:5002"
    networks:
      - my-network 


  events.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5003:5003"
    networks:
      - my-network 

networks:
  my-network:
    driver: bridge 




